#!/bin/bash

echo "#%%%%%%%%%%%%%%%%%%%%%%%%%%%%#
# Input for Frenkel coupling #
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%#


##Parameter for Amber and gaussian
PDB :           protein.pdb
PRMTOP :        protein.prmtop
trajectory :    protein.nc

Level of theory : B3LYP/6-311+G**
Number of state : 5

Full calculation : n

##Parameter for Frenkel coupling
#Type of coupling (chose one)
Perturbation :     y
Matrix :           y

#Specify the spectral window (nm)
lower limit :    250
upper limit :    320

##Parameter for convolution (Don't touch)
#Resolution (nm)
resolution :     0.5

#Full width at half maximum (eV)
fwhm :    0.2

"> QmmmInput 

