#!/bin/bash

#Launch QMMM directory and file for each residus

input=$1

Nresid=`head -n +1 geometry.dat | awk '{print $1}'`
prmtop_file=`grep 'PRMTOP' $input | awk '{print $3}'`
lot=`grep 'Level of theory' $input | awk '{print $5}'`
NStates=`grep 'Number of state' $input | awk '{print $5}'`
full=`grep 'Full calculation' $input | awk '{print $4}'`

work_file=`pwd`



for rep in R-*/ ; do
 cd $rep

   mkdir state_1
   cp ../submith.sh state_1
   cp ../gau_job.tpl state_1
   cp mdgau-min protein.rst $prmtop_file state_1
   cd state_1
    sed -i -e "s/x/1/g" gau_job.tpl
    sbatch submith.sh
   cd ..
 
  if [ "$full" = "y" ]; then
   for i in $( eval echo {2..$NStates}); do
    mkdir state_$i
    cp ../submith.sh state_$i
    cp ../gau_job.tpl state_$i
    cp mdgau-min protein.rst $prmtop_file state_$i
    cd state_$i
     sed -i -e "s/x/$i/g" gau_job.tpl
     sbatch submith.sh
    cd ..
   done
  
   mkdir state_0
   cp ../submith.sh state_0
   cp mdgau-min protein.rst $prmtop_file state_0
   cd state_0
    echo "# $lot density" > gau_job.tpl
    sbatch submith.sh
   cd ..
  fi
 cd ..
done

#if [[ -f "terminaison" ]]; then
# rm terminaison
#fi
#touch terminaison
#
#N=`cat terminaison | wc -l`
#while [ $N -lt $(( $Nresid * $(( $NStates + 1)) )) ]; do
#   sleep 60
#   N=`cat $work_file/terminaison | wc -l`
#done
#rm terminaison
# echo "done"
#
#prep_frenkel QmmmInput
#
#cd frenkel_spectrum
#frenkel FrenkelInput
#cd ..

