#!/bin/bash

input=$1

mkdir frenkel_spectrum
mkdir frenkel_spectrum/G09_output

pdb_file=`grep 'PDB' $input | awk '{print $3}'`

for res in R-* ; do
 for i in {0..5}; do 
  mv $res/state_$i/old.gau_job.log frenkel_spectrum/G09_output/$res-S$i.log
 done
 rm -rf $res
done

cp $pdb_file frenkel_spectrum
cp geometry.dat frenkel_spectrum

cd frenkel_spectrum 

#Preparation of the Frenkel input

echo '#%%%%%%%%%%%%%%%%%%%%%%%%%%%%#
# Input for Frenkel coupling #
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%#

#--Aromatic--#' > FrenkelInput

for res in G09_output/R-arom-*-S1.log; do
 if [[ "$res" != "G09_output/R-arom-*-S1.log" ]]; then
  num=${res%"-S1.log"}
  num=${num#"G09_output/R-arom-"}
  file=${res%"-S1.log"}
  file=${file#"G09_output/"}
  echo "$file $num" >> FrenkelInput
 fi
done

echo '#--SS Bridge--#' >> FrenkelInput

for res in G09_output/R-ss-*-S1.log; do
 if [[ "$res" != "G09_output/R-ss-*-S1.log" ]]; then
  num=${res%"-S1.log"}
  num=${num#"G09_output/R-ss-"}
  file=${res%"-S1.log"}
  file=${file#"G09_output/"}
  IFS=- read -r num1 num2 <<< $num 
  echo "$file $num1 $num2" >> FrenkelInput
 fi
done

echo '#----#
' >> FrenkelInput

grep PDB ../$input >> FrenkelInput
grep "Number of state" ../$input >> FrenkelInput
grep "Full calculation" ../$input >> FrenkelInput

echo '
##Parameter for Frenkel coupling
#Type of coupling (chose one)' >> FrenkelInput

grep 'Perturbation' ../$input >> FrenkelInput
grep 'Matrix' ../$input >> FrenkelInput

echo '
#Specify the spectral window (nm)' >> FrenkelInput

grep 'lower limit' ../$input >> FrenkelInput
grep 'upper limit' ../$input >> FrenkelInput

echo "
##Parameter for convolution (Don't touch)
#Resolution (nm)"  >> FrenkelInput

grep 'resolution' ../$input >> FrenkelInput

echo "
#Full width at half maximum (eV)" >> FrenkelInput

grep 'fwhm' ../$input >> FrenkelInput

