#!/bin/bash

module purge
module load intelmpi/2019.4
module load mcs_mod/compenv/intel/2019.4

# Compiler.
FC='ifort' 

# Compilation parameters.

### For execution
FFLAGS='-O2 -g -c'

LFLAGS='-lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -liomp5 -lpthread -O2'

# Defines a .o for any file entering the compilation.
OBJS='declare.o deal.o strip_space.o find_number_PAR.o rpdb.o com.o normal_vect.o distance.o angle.o min_distance.o cnorm.o store_ss.o woutput.o main_geometry.o'

# Command line for the creation of the .o files.
$FC $FFLAGS declare.f90
$FC $FFLAGS *.f90

# Creation of the main file.
$FC $OBJS $LFLAGS -o geometry
#$FC $OBJS -o geometry

#ifort declare.f90 deal.f90 geometry.f90 -o geometry_2



# Removal of the .o files after their compilation into the main file.
rm -f *.o *.mod

echo done
