#!/bin/bash

### Path to intel and mkl libraries 

module purge
module load intel/2019.4
module load mkl/2019.4

### Path to Amber16 and Gaussian09

path_amber='amber/16'
path_gaussian='gaussian/09/pgi'

cd executable
  sed -i "/path_amber=/c path_amber='$path_amber'" prep_*
  sed -i "/path_gaussian=/c path_gaussian='$path_gaussian'" prep_*
cd ..

### Compilation parameters

# Compiler.
FC='ifort' 
# Flags for execution
FFLAGS='-O2 -g -c'
# Sets the libraries 
LFLAGS='-lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -liomp5 -lpthread -O3'


### Geometry analysis compilation

cd geometry_prog

echo "
Geometry analysis compilation ..."

# Defines a .o for any file entering the compilation.
OBJS='declare.o deal.o strip_space.o find_number_PAR.o rpdb.o coc.o normal_vect.o distance.o angle.o min_distance.o cnorm.o store_ss.o woutput.o main_geometry.o'

# Command line for the creation of the .o files.
$FC $FFLAGS declare.f90
$FC $FFLAGS *.f90

# Creation of the main file.
$FC $OBJS $LFLAGS -o geometry

# Removal of the .o files after their compilation into the main file.
rm -f *.o *.mod

mv geometry ../executable

echo "The geometry executable has been created
"

#mv geometry ../executable

cd ..
###

### DrichroProt compilation
cd dichroprot_prog

echo "dichroprot compilation ..."

# Defines a .o for any file entering the compilation.
OBJS='declare.o deal.o rinput.o rlog.o rpdb.o coc.o distance.o dip_dip_coupling.o H_build.o H_diag.o convolution.o cpl_perturbation.o cpl_matrix.o cpl_superposition.o main_dichroprot.o'

# Command line for the creation of the .o files.
$FC $FFLAGS declare.f90
$FC $FFLAGS *.f90

# Creation of the main file.
$FC $OBJS $LFLAGS -o dichroprot

# Removal of the .o files after their compilation into the main file.
rm -f *.o *.mod

mv dichroprot ../executable

echo "The dichroprot executable has been created
"
cd ..


### Other program compilation

echo "Other programs compilation ..."
cd other_prog
echo "   - Average spectrum compilation "
$FC $LFLAGS average_spectrum.f90 -o average_spectrum

# Removal of the .o files after their compilation into the main file.
rm -f *.o *.mod
mv average_spectrum ../executable

echo "All other executables has been created
"
 

cd ..
###

echo "All executables has been moved to the executable repository
"

