#!/bin/bash


rm -rf R-*

if [ -d "gau_job.tpl" ]; then
   rm gau_job.tpl
fi

if [ -d "submith.sh" ]; then
   rm gau_job.tpl
fi

if [ -d "trajin" ]; then
   rm gau_job.tpl
fi

if [ ! -d "/spectrum_backup" ]; then
   mkdir spectrum_backup
fi


if [ -d "/frenkel_spectrum" ]; then 
  N_bck=`ls -1 spectrum_backup | wc -l`
  echo $N_bck
  #mv frenkel_spectrum frenkel_spectrum-$N_bck
  #mv frenkel_spectrum-$N_bck /spectrum_backup
fi

