#!/bin/bash

input=$1
NStates=`grep 'Number of state' $input | awk '{print $5}'`
full=`grep 'Full contribution' $input | awk '{print $4}'`

mkdir DichroProt
mkdir DichroProt/G09_output
mkdir DichroProt/G09_fchk

pdb_file=`grep 'PDB' $input | awk '{print $3}'`

#Gather all Gaussian output
for res in R-* ; do
 mv $res/state_1/old.gau_job.log DichroProt/G09_output/$res-S1.log
 mv $res/state_1/gau_job.fchk DichroProt/G09_fchk/$res-S1.fchk
 
 if [ "$full" = "y" ]; then
  mv $res/state_0/old.gau_job.log DichroProt/G09_output/$res-S0.log
  mv $res/state_0/gau_job.fchk DichroProt/G09_fchk/$res-S0.fchk 

  for i in {2..$NStates}; do 
   mv $res/state_$i/old.gau_job.log DichroProt/G09_output/$res-S$i.log
   mv $res/state_$i/gau_job.fchk DichroProt/G09_fchk/$res-S$i.fchk
  done
 fi
 rm -rf $res
done

cp $pdb_file DichroProt
cp geometry.dat DichroProt

cd DichroProt

#Preparation of the DichroProt input

echo "#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#
# Input for DichroProt coupling #
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#

#--Aromatic--#' > DichroProtInput

for res in G09_output/R-arom-*-S1.log; do
 if [[ "$res" != "G09_output/R-arom-*-S1.log" ]]; then
  num=${res%"-S1.log"}
  num=${num#"G09_output/R-arom-"}
  file=${res%"-S1.log"}
  file=${file#"G09_output/"}
  echo "$file $num" >> DichroProtInput
 fi
done

echo '#--SS Bridge--#' >> DichroProtInput

for res in G09_output/R-ss-*-S1.log; do
 if [[ "$res" != "G09_output/R-ss-*-S1.log" ]]; then
  num=${res%"-S1.log"}
  num=${num#"G09_output/R-ss-"}
  file=${res%"-S1.log"}
  file=${file#"G09_output/"}
  IFS=- read -r num1 num2 <<< $num 
  echo "$file $num1 $num2" >> DichroProtInput
 fi
done

echo '#----#
' >> DichroProtInput

grep PDB ../$input >> DichroProtInput
grep "Number of state" ../$input >> DichroProtInput
grep "Full contribution" ../$input >> DichroProtInput

echo '
##Parameter for coupling
#Type of coupling (chose one)' >> DichroProtInput

grep 'Perturbation' ../$input >> DichroProtInput
grep 'Matrix' ../$input >> DichroProtInput
grep 'Superposition' ../$input >> DichroProtInput

echo '
#Specify the spectral window (nm)' >> DichroProtInput

grep 'lower limit' ../$input >> DichroProtInput
grep 'upper limit' ../$input >> DichroProtInput

echo "
##Parameter for convolution (Don't touch)
#Resolution (nm)"  >> DichroProtInput

grep 'resolution' ../$input >> DichroProtInput

echo "
#Full width at half maximum (eV)" >> DichroProtInput

grep 'fwhm' ../$input >> DichroProtInput

