#!/bin/bash

input=$1

# Read input
trajectory=`grep 'trajectory' $input | awk '{print $3}'`
prmtop_file=`grep 'PRMTOP' $input | awk '{print $3}'`
pdb_file=${prmtop_file%".prmtop"}
lot=`grep 'Level of theory' $input | awk '{print $5}'`
NStates=`grep 'Number of state' $input | awk '{print $5}'`
full=`grep 'Full contribution' $input | awk '{print $4}'`
pertur=`grep 'Perturbation' $input | awk '{print $3}'`
matrix=`grep 'Matrix' $input | awk '{print $3}'`
superp=`grep 'Superposition' $input | awk '{print $3}'`
lower=`grep 'lower limit' $input | awk '{print $4}'`
upper=`grep 'upper limit' $input | awk '{print $4}'`
resolution=`grep 'resolution' $input | awk '{print $3}'`
fwhm=`grep 'fwhm' $input | awk '{print $3}'`

# Create conformation
mkdir conformation
cd conformation

echo "parm ../$prmtop_file
trajin ../$trajectory 1 last 20

trajout $pdb_file pdb multi
" > trajin_pdb

module load amber/16
cpptraj < trajin_pdb

N_frame=`ls | wc -l`
N_frame=$((N_frame-1))

#In case some error appear in the creation of the .pdb file
#We erase the corrupted frame and renumber every other one
for (( i=1; i<=$N_frame; i++ )); do
 test_X=`head -n2 $pdb_file.$i | tail -n1 | awk '{print $6}'`
 test_Y=`head -n2 $pdb_file.$i | tail -n1 | awk '{print $7}'`
 test_Z=`head -n2 $pdb_file.$i | tail -n1 | awk '{print $8}'`

 if [ "$test_X" = "0.000" ]; then
  if [ "$test_Y" = "0.000" ]; then
   if [ "$test_Z" = "0.000" ]; then
echo "elimine frame $i"
    for (( j=$(( $i + 1 )); j<=$N_frame; j++ )); do
     mv $pdb_file.$j $pdb_file.$(( $j - 1 ))
    done
    i=$(( $i - 1))
    N_frame=$(( $N_frame - 1))
   fi
  fi
 fi
done

cd ..


for (( i=1; i<=$N_frame; i++ )); do

  mkdir frame_$i

  mv conformation/$pdb_file.$i frame_$i/$pdb_file.$i.pdb

  cp $prmtop_file frame_$i

  cd frame_$i

echo "#%%%%%%%%%%%%%%%%%%%%%%%%%%%%#
# Input for Frenkel coupling #
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%#


##Parameter for Amber and gaussian
PDB :           $pdb_file.$i.pdb
PRMTOP :        $prmtop_file
trajectory :    protein.nc
Number of frame : $N_frame 

Level of theory : $lot
Number of state : $NStates

Full contribution : $full

##Parameter for Frenkel coupling
#Type of coupling (chose one)
Perturbation :     $pertur
Matrix :           $matrix
Superposition :    $superp

#Specify the spectral window (nm)
lower limit :    $lower
upper limit :    $upper

##Parameter for convolution (Don't touch)
#Resolution (nm)
resolution :     $resolution

#Full width at half maximum (eV)
fwhm :    $fwhm

" > QmmmInput

  prep_qmmm QmmmInput

  cd ..

done

echo "Number of frame : $N_frame" >> $input
rm -rf conformation

