#!/bin/bash

module purge
#module load intelmpi/2019.4
module load mcs_mod/compenv/intel/2019.4


### Compilation parameters

# Compiler.
FC='ifort' 
# Flags for execution
FFLAGS='-O2 -g -c'
# Sets the libraries 
LFLAGS='-lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -liomp5 -lpthread -O2'


### Geometry analysis compilation

if [ 1 = 2 ]; then 

cd geometry_prog

echo "
Geometry analysis compilation ..."

# Defines a .o for any file entering the compilation.
OBJS='declare.o deal.o strip_space.o find_number_PAR.o rpdb.o com.o normal_vect.o distance.o angle.o min_distance.o cnorm.o store_ss.o woutput.o main_geometry.o'

# Command line for the creation of the .o files.
$FC $FFLAGS declare.f90
$FC $FFLAGS *.f90

# Creation of the main file.
$FC $OBJS $LFLAGS -o geometry

# Removal of the .o files after their compilation into the main file.
rm -f *.o *.mod

echo "The geometry executable has been created
"

cd ..
fi

### Frenkel coupling compilation
cd frenkel_prog

echo "Frenkel coupling compilation ..."

# Defines a .o for any file entering the compilation.
OBJS='declare.o deal.o rinput.o rlog.o rpdb.o com.o distance.o dip_dip_coupling.o H_build.o H_diag.o convolution.o cpl_perturbation.o cpl_matrix.o main_frenkel.o'

# Command line for the creation of the .o files.
$FC $FFLAGS declare.f90
$FC $FFLAGS *.f90

# Creation of the main file.
$FC $OBJS $LFLAGS -o frenkel

# Removal of the .o files after their compilation into the main file.
rm -f *.o *.mod

echo "The frenkel executable has been created
"

cd ..
#mv frenkel_prog/frenkel geometry_prog/geometry executable

mv frenkel_prog/frenkel executable

echo "All executables has been moved to the executable repository
"

